---
############################
# Play01 - 웹서버 설정
# 1) 패키지 설치
# 2) 서비스 기동
# 3) 방화벽 등록
############################
- name: Play01 - 웹서버 설정
  hosts: webserver
  tasks: 
    - name: 패키지 설치 - httpd
      ansible.builtin.dnf:
        name: "{{ ansible_local['custom']['general']['package'] }}"
        state: present

    - name: 서비스 기동 - httpd
      ansible.builtin.systemd_service:
        state: "{{ ansible_local['custom']['general']['state'] }}"
        name: "{{ ansible_local['custom']['general']['service'] }}"
        enabled: true

    - name: 서비스 기동 - firewalld
      ansible.builtin.systemd_service:
        state: "{{ ansible_local['custom']['general']['state'] }}"
        name: firewalld
        enabled: true

    - name: 방화벽 등록 - httpd
      ansible.posix.firewalld:
        service: "{{ ansible_local['custom']['general']['fwsvc'] }}"
        state: enabled
        permanent: true
        immediate: true



